version: "3.9"

services:
  test123:
    image: test123:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test123
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3002:3000"