version: "3.8"

services:
    client:
        container_name: phianhcv-fe
        image: phianhcv:latest
        build: .
    nginx:
        container_name: phianhcv-nginx-client
        build: ./nginx
        ports:
            - 3003:80
