name: Publish CV

on:
  push:
    branches: [ cv/giang ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        docker compose build
        docker save -o build.tar giangcv-fe:latest

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

    - name: Copy tar file to VPS
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} uptime
        scp build.tar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/Project/SmallProject/CV-Online-Template          

    - name: Load Docker image on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/Project/SmallProject/CV-Online-Template
          sh deploy.sh